# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_product_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChooseProduct(object):
    def setupUi(self, ChooseProduct):
        ChooseProduct.setObjectName("ChooseProduct")
        ChooseProduct.resize(706, 375)
        self.centralwidget = QtWidgets.QWidget(ChooseProduct)
        self.centralwidget.setObjectName("centralwidget")
        self.add_to_cart_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_to_cart_button.setGeometry(QtCore.QRect(10, 10, 121, 41))
        self.add_to_cart_button.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.add_to_cart_button.setObjectName("add_to_cart_button")
        self.products_table_widget = QtWidgets.QTableWidget(self.centralwidget)
        self.products_table_widget.setGeometry(QtCore.QRect(150, 10, 541, 311))
        self.products_table_widget.setObjectName("products_table_widget")
        self.products_table_widget.setColumnCount(0)
        self.products_table_widget.setRowCount(0)
        self.add_to_cart_by_sku_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_to_cart_by_sku_button.setGeometry(QtCore.QRect(10, 70, 121, 41))
        self.add_to_cart_by_sku_button.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.add_to_cart_by_sku_button.setObjectName("add_to_cart_by_sku_button")
        self.sort_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.sort_combo_box.setGeometry(QtCore.QRect(260, 340, 141, 22))
        self.sort_combo_box.setObjectName("sort_combo_box")
        self.sort_combo_box.addItem("")
        self.sort_combo_box.addItem("")
        self.sort_combo_box.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 340, 111, 16))
        self.label.setObjectName("label")
        ChooseProduct.setCentralWidget(self.centralwidget)

        self.retranslateUi(ChooseProduct)
        QtCore.QMetaObject.connectSlotsByName(ChooseProduct)

    def retranslateUi(self, ChooseProduct):
        _translate = QtCore.QCoreApplication.translate
        ChooseProduct.setWindowTitle(_translate("ChooseProduct", "Добавление продукта в заказ"))
        self.add_to_cart_button.setText(_translate("ChooseProduct", "Выбрать продукт"))
        self.add_to_cart_by_sku_button.setText(_translate("ChooseProduct", "Ввести уникальный \n"
"номер"))
        self.sort_combo_box.setItemText(0, _translate("ChooseProduct", "Название"))
        self.sort_combo_box.setItemText(1, _translate("ChooseProduct", "Номер товара"))
        self.sort_combo_box.setItemText(2, _translate("ChooseProduct", "Название(обратный порядок)"))
        self.label.setText(_translate("ChooseProduct", "Сортировать по:"))
