# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_order_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrderCreate(object):
    def setupUi(self, OrderCreate):
        OrderCreate.setObjectName("OrderCreate")
        OrderCreate.resize(774, 404)
        self.centralwidget = QtWidgets.QWidget(OrderCreate)
        self.centralwidget.setObjectName("centralwidget")
        self.add_product_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_product_button.setGeometry(QtCore.QRect(10, 20, 131, 41))
        self.add_product_button.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.add_product_button.setObjectName("add_product_button")
        self.remove_product_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_product_button.setGeometry(QtCore.QRect(10, 80, 131, 41))
        self.remove_product_button.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.remove_product_button.setObjectName("remove_product_button")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(160, 10, 601, 381))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.add_order_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_order_button.setGeometry(QtCore.QRect(10, 340, 131, 41))
        self.add_order_button.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.add_order_button.setObjectName("add_order_button")
        OrderCreate.setCentralWidget(self.centralwidget)

        self.retranslateUi(OrderCreate)
        QtCore.QMetaObject.connectSlotsByName(OrderCreate)

    def retranslateUi(self, OrderCreate):
        _translate = QtCore.QCoreApplication.translate
        OrderCreate.setWindowTitle(_translate("OrderCreate", "Оформление заказа"))
        self.add_product_button.setText(_translate("OrderCreate", "Добавить позицию"))
        self.remove_product_button.setText(_translate("OrderCreate", "Удалить позицию"))
        self.add_order_button.setText(_translate("OrderCreate", "Оформить заказ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    phone_info = QtWidgets.QMainWindow()
    ui = Ui_OrderCreate()
    ui.setupUi(phone_info)
    phone_info.show()
    sys.exit(app.exec_())