# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orders_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrdersMenu(object):
    def setupUi(self, OrdersMenu):
        OrdersMenu.setObjectName("OrdersMenu")
        OrdersMenu.resize(800, 438)
        self.centralwidget = QtWidgets.QWidget(OrdersMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.add_order_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_order_button.setGeometry(QtCore.QRect(10, 10, 141, 41))
        self.add_order_button.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.add_order_button.setObjectName("add_order_button")
        self.remove_order_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_order_button.setGeometry(QtCore.QRect(10, 70, 141, 41))
        self.remove_order_button.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.remove_order_button.setObjectName("remove_order_button")
        self.orders_table_widget = QtWidgets.QTableWidget(self.centralwidget)
        self.orders_table_widget.setGeometry(QtCore.QRect(160, 10, 621, 371))
        self.orders_table_widget.setObjectName("orders_table_widget")
        self.orders_table_widget.setColumnCount(0)
        self.orders_table_widget.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 400, 131, 16))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.sort_info_box = QtWidgets.QComboBox(self.centralwidget)
        self.sort_info_box.setGeometry(QtCore.QRect(310, 400, 111, 22))
        self.sort_info_box.setObjectName("sort_info_box")
        self.sort_info_box.addItem("")
        self.sort_info_box.addItem("")
        self.sort_info_box.addItem("")
        self.change_order_button = QtWidgets.QPushButton(self.centralwidget)
        self.change_order_button.setGeometry(QtCore.QRect(10, 130, 141, 41))
        self.change_order_button.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.change_order_button.setObjectName("change_order_button")
        OrdersMenu.setCentralWidget(self.centralwidget)

        self.retranslateUi(OrdersMenu)
        QtCore.QMetaObject.connectSlotsByName(OrdersMenu)

    def retranslateUi(self, OrdersMenu):
        _translate = QtCore.QCoreApplication.translate
        OrdersMenu.setWindowTitle(_translate("OrdersMenu", "Менеджер заказов"))
        self.add_order_button.setText(_translate("OrdersMenu", "Добавить заказ"))
        self.remove_order_button.setText(_translate("OrdersMenu", "Удалить заказ"))
        self.label.setText(_translate("OrdersMenu", "Отсортировать по:"))
        self.sort_info_box.setItemText(0, _translate("OrdersMenu", "Номер заказа"))
        self.sort_info_box.setItemText(1, _translate("OrdersMenu", "Имя клиента"))
        self.sort_info_box.setItemText(2, _translate("OrdersMenu", "Дата"))
        self.change_order_button.setText(_translate("OrdersMenu", "Изменить заказ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    phone_info = QtWidgets.QMainWindow()
    ui = Ui_OrdersMenu()
    ui.setupUi(phone_info)
    phone_info.show()
    sys.exit(app.exec_())