# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'products_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProductMenu(object):
    def setupUi(self, ProductMenu):
        ProductMenu.setObjectName("ProductMenu")
        ProductMenu.resize(789, 395)
        self.centralwidget = QtWidgets.QWidget(ProductMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.add_new_product_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_new_product_button.setGeometry(QtCore.QRect(10, 10, 121, 41))
        self.add_new_product_button.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.add_new_product_button.setObjectName("add_new_product_button")
        self.remove_product_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_product_button.setGeometry(QtCore.QRect(10, 60, 121, 41))
        self.remove_product_button.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.remove_product_button.setObjectName("remove_product_button")
        self.edit_product_button = QtWidgets.QPushButton(self.centralwidget)
        self.edit_product_button.setGeometry(QtCore.QRect(10, 110, 121, 41))
        self.edit_product_button.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.edit_product_button.setObjectName("edit_product_button")
        self.products_table_widget = QtWidgets.QTableWidget(self.centralwidget)
        self.products_table_widget.setGeometry(QtCore.QRect(150, 10, 621, 331))
        self.products_table_widget.setObjectName("products_table_widget")
        self.products_table_widget.setColumnCount(0)
        self.products_table_widget.setRowCount(0)
        self.search_by_name_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_by_name_button.setGeometry(QtCore.QRect(10, 300, 121, 41))
        self.search_by_name_button.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.search_by_name_button.setObjectName("search_by_name_button")
        self.sort_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.sort_combo_box.setGeometry(QtCore.QRect(250, 360, 141, 22))
        self.sort_combo_box.setObjectName("sort_combo_box")
        self.sort_combo_box.addItem("")
        self.sort_combo_box.addItem("")
        self.sort_combo_box.addItem("")
        self.sort_combo_box.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 360, 111, 16))
        self.label.setObjectName("label")
        self.refresh_button = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_button.setGeometry(QtCore.QRect(10, 250, 121, 41))
        self.refresh_button.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.refresh_button.setObjectName("refresh_button")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(410, 360, 101, 17))
        self.checkBox.setObjectName("checkBox")
        ProductMenu.setCentralWidget(self.centralwidget)

        self.retranslateUi(ProductMenu)
        QtCore.QMetaObject.connectSlotsByName(ProductMenu)

    def retranslateUi(self, ProductMenu):
        _translate = QtCore.QCoreApplication.translate
        ProductMenu.setWindowTitle(_translate("ProductMenu", "Редактор продуктов"))
        self.add_new_product_button.setText(_translate("ProductMenu", "Добавить продукт"))
        self.remove_product_button.setText(_translate("ProductMenu", "Удалить продукт"))
        self.edit_product_button.setText(_translate("ProductMenu", "Изменить продукт"))
        self.search_by_name_button.setText(_translate("ProductMenu", "Поиск продукта"))
        self.sort_combo_box.setItemText(0, _translate("ProductMenu", "Название"))
        self.sort_combo_box.setItemText(1, _translate("ProductMenu", "Номер товара"))
        self.sort_combo_box.setItemText(2, _translate("ProductMenu", "Цена"))
        self.sort_combo_box.setItemText(3, _translate("ProductMenu", "Категория"))
        self.label.setText(_translate("ProductMenu", "Сортировать по:"))
        self.refresh_button.setText(_translate("ProductMenu", "Обновить"))
        self.checkBox.setText(_translate("ProductMenu", "По убыванию"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProductMenu = QtWidgets.QMainWindow()
    ui = Ui_ProductMenu()
    ui.setupUi(ProductMenu)
    ProductMenu.show()
    sys.exit(app.exec_())
