# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'products_button.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_products(object):
    def setupUi(self, products):
        products.setObjectName("products")
        products.resize(357, 515)
        self.centralwidget = QtWidgets.QWidget(products)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 90, 68, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 150, 91, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 210, 141, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 360, 91, 19))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 30, 251, 19))
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 120, 141, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 180, 141, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 240, 141, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 480, 151, 19))
        self.label_6.setObjectName("label_6")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 390, 261, 71))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 320, 121, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        products.setCentralWidget(self.centralwidget)

        self.retranslateUi(products)
        QtCore.QMetaObject.connectSlotsByName(products)

    def retranslateUi(self, products):
        _translate = QtCore.QCoreApplication.translate
        products.setWindowTitle(_translate("products", "MainWindow"))
        self.label.setText(_translate("products", "Имя*:"))
        self.label_2.setText(_translate("products", "Фамилия*:"))
        self.label_3.setText(_translate("products", "Номер телефона*:"))
        self.label_4.setText(_translate("products", "Заметки:"))
        self.label_5.setText(_translate("products", "Введите информацию о клиенте"))
        self.label_6.setText(_translate("products", "* - обязательно"))
        self.pushButton.setText(_translate("products", "Перейти к заказу"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    products = QtWidgets.QMainWindow()
    ui = Ui_products()
    ui.setupUi(products)
    products.show()
    sys.exit(app.exec_())
