# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warehouse_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_warehouse_info(object):
    def setupUi(self, warehouse_info):
        warehouse_info.setObjectName("warehouse_info")
        warehouse_info.resize(957, 681)
        self.centralwidget = QtWidgets.QWidget(warehouse_info)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 70, 881, 541))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(40, 30, 161, 25))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 630, 211, 19))
        self.label.setObjectName("label")
        self.value = QtWidgets.QLabel(self.centralwidget)
        self.value.setGeometry(QtCore.QRect(260, 630, 251, 19))
        self.value.setObjectName("value")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 71, 19))
        self.label_2.setObjectName("label_2")
        warehouse_info.setCentralWidget(self.centralwidget)

        self.retranslateUi(warehouse_info)
        QtCore.QMetaObject.connectSlotsByName(warehouse_info)

    def retranslateUi(self, warehouse_info):
        _translate = QtCore.QCoreApplication.translate
        warehouse_info.setWindowTitle(_translate("warehouse_info", "MainWindow"))
        self.label.setText(_translate("warehouse_info", "Общее количество товара:"))
        self.value.setText(_translate("warehouse_info", "*value*"))
        self.label_2.setText(_translate("warehouse_info", "Cклад:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    warehouse_info = QtWidgets.QMainWindow()
    ui = Ui_warehouse_info()
    ui.setupUi(warehouse_info)
    warehouse_info.show()
    sys.exit(app.exec_())
