# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customer_information.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomerInfo(object):
    def setupUi(self, CustomerInfo):
        CustomerInfo.setObjectName("CustomerInfo")
        CustomerInfo.resize(388, 227)
        self.centralwidget = QtWidgets.QWidget(CustomerInfo)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 91, 16))
        self.label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 141, 16))
        self.label_2.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 111, 16))
        self.label_3.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.customer_name_label = QtWidgets.QLabel(self.centralwidget)
        self.customer_name_label.setGeometry(QtCore.QRect(60, 50, 151, 16))
        self.customer_name_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.customer_name_label.setObjectName("customer_name_label")
        self.custome_lastname_label = QtWidgets.QLabel(self.centralwidget)
        self.custome_lastname_label.setGeometry(QtCore.QRect(90, 90, 131, 16))
        self.custome_lastname_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.custome_lastname_label.setObjectName("custome_lastname_label")
        self.customer_phone_label = QtWidgets.QLabel(self.centralwidget)
        self.customer_phone_label.setGeometry(QtCore.QRect(140, 130, 161, 16))
        self.customer_phone_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.customer_phone_label.setObjectName("customer_phone_label")
        self.customer_notes_button = QtWidgets.QPushButton(self.centralwidget)
        self.customer_notes_button.setGeometry(QtCore.QRect(20, 180, 81, 31))
        self.customer_notes_button.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.customer_notes_button.setObjectName("customer_notes_button")
        self.customer_orders_button = QtWidgets.QPushButton(self.centralwidget)
        self.customer_orders_button.setGeometry(QtCore.QRect(110, 180, 81, 31))
        self.customer_orders_button.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.customer_orders_button.setObjectName("customer_orders_button")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(110, 20, 191, 16))
        self.label_7.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_7.setObjectName("label_7")
        self.change_customer_info_button = QtWidgets.QPushButton(self.centralwidget)
        self.change_customer_info_button.setGeometry(QtCore.QRect(200, 180, 81, 31))
        self.change_customer_info_button.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.change_customer_info_button.setObjectName("change_customer_info_button")
        self.customer_remove_button = QtWidgets.QPushButton(self.centralwidget)
        self.customer_remove_button.setGeometry(QtCore.QRect(290, 180, 81, 31))
        self.customer_remove_button.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.customer_remove_button.setObjectName("customer_remove_button")
        CustomerInfo.setCentralWidget(self.centralwidget)

        self.retranslateUi(CustomerInfo)
        QtCore.QMetaObject.connectSlotsByName(CustomerInfo)

    def retranslateUi(self, CustomerInfo):
        _translate = QtCore.QCoreApplication.translate
        CustomerInfo.setWindowTitle(_translate("CustomerInfo", "Информация о клиенте"))
        self.label.setText(_translate("CustomerInfo", "Имя:"))
        self.label_2.setText(_translate("CustomerInfo", "Фамилия:"))
        self.label_3.setText(_translate("CustomerInfo", "Номер телефона:"))
        self.customer_name_label.setText(_translate("CustomerInfo", "*name*"))
        self.custome_lastname_label.setText(_translate("CustomerInfo", "*lastname*"))
        self.customer_phone_label.setText(_translate("CustomerInfo", "*phone*"))
        self.customer_notes_button.setText(_translate("CustomerInfo", "Заметки"))
        self.customer_orders_button.setText(_translate("CustomerInfo", "Заказы"))
        self.label_7.setText(_translate("CustomerInfo", "Информация о клиенте"))
        self.change_customer_info_button.setText(_translate("CustomerInfo", "Изменить"))
        self.customer_remove_button.setText(_translate("CustomerInfo", "Удалить"))
