# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(280, 375)
        self.centralwidget = QtWidgets.QWidget(Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.orders_button = QtWidgets.QPushButton(self.centralwidget)
        self.orders_button.setGeometry(QtCore.QRect(20, 20, 241, 51))
        self.orders_button.setStyleSheet("font: 11pt \"Nirmala UI Semilight\";")
        self.orders_button.setObjectName("orders_button")
        self.products_button = QtWidgets.QPushButton(self.centralwidget)
        self.products_button.setGeometry(QtCore.QRect(20, 80, 241, 51))
        self.products_button.setStyleSheet("font: 11pt \"Nirmala UI Semilight\";")
        self.products_button.setObjectName("products_button")
        self.customers_button = QtWidgets.QPushButton(self.centralwidget)
        self.customers_button.setGeometry(QtCore.QRect(20, 160, 241, 51))
        self.customers_button.setStyleSheet("font: 11pt \"Nirmala UI Semilight\";")
        self.customers_button.setObjectName("customers_button")
        self.warehouses_button = QtWidgets.QPushButton(self.centralwidget)
        self.warehouses_button.setGeometry(QtCore.QRect(20, 220, 241, 51))
        self.warehouses_button.setStyleSheet("font: 11pt \"Nirmala UI Semilight\";")
        self.warehouses_button.setObjectName("warehouses_button")
        self.admins_button = QtWidgets.QPushButton(self.centralwidget)
        self.admins_button.setGeometry(QtCore.QRect(20, 300, 241, 51))
        self.admins_button.setStyleSheet("font: 11pt \"Nirmala UI Semilight\";")
        self.admins_button.setObjectName("admins_button")
        Menu.setCentralWidget(self.centralwidget)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Главное меню"))
        self.orders_button.setText(_translate("Menu", "Менеджер заказов"))
        self.products_button.setText(_translate("Menu", "Редактор продуктов"))
        self.customers_button.setText(_translate("Menu", "Клиентский центр"))
        self.warehouses_button.setText(_translate("Menu", "Инвентаризация по складам"))
        self.admins_button.setText(_translate("Menu", "Меню администратора"))
