# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_customer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_about_customer(object):
    def setupUi(self, about_customer):
        about_customer.setObjectName("about_customer")
        about_customer.resize(796, 593)
        self.centralwidget = QtWidgets.QWidget(about_customer)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 20, 731, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 460, 41, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 490, 81, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 520, 131, 19))
        self.label_3.setObjectName("label_3")
        self.firstname = QtWidgets.QLabel(self.centralwidget)
        self.firstname.setGeometry(QtCore.QRect(80, 460, 221, 19))
        self.firstname.setObjectName("firstname")
        self.lastname = QtWidgets.QLabel(self.centralwidget)
        self.lastname.setGeometry(QtCore.QRect(120, 490, 221, 19))
        self.lastname.setObjectName("lastname")
        self.number = QtWidgets.QLabel(self.centralwidget)
        self.number.setGeometry(QtCore.QRect(180, 520, 221, 19))
        self.number.setObjectName("number")
        self.remove_order = QtWidgets.QPushButton(self.centralwidget)
        self.remove_order.setGeometry(QtCore.QRect(620, 460, 141, 31))
        self.remove_order.setObjectName("remove_order")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(620, 500, 141, 31))
        self.save_button.setObjectName("save_button")
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(620, 540, 141, 31))
        self.reset_button.setObjectName("reset_button")
        self.notes_button = QtWidgets.QPushButton(self.centralwidget)
        self.notes_button.setGeometry(QtCore.QRect(40, 550, 141, 31))
        self.notes_button.setObjectName("notes_button")
        about_customer.setCentralWidget(self.centralwidget)

        self.retranslateUi(about_customer)
        QtCore.QMetaObject.connectSlotsByName(about_customer)

    def retranslateUi(self, about_customer):
        _translate = QtCore.QCoreApplication.translate
        about_customer.setWindowTitle(_translate("about_customer", "MainWindow"))
        self.label.setText(_translate("about_customer", "Имя:"))
        self.label_2.setText(_translate("about_customer", "Фамилия:"))
        self.label_3.setText(_translate("about_customer", "Номер телефона:"))
        self.firstname.setText(_translate("about_customer", "*firstname*"))
        self.lastname.setText(_translate("about_customer", "*lastname*"))
        self.number.setText(_translate("about_customer", "*number*"))
        self.remove_order.setText(_translate("about_customer", "Удалить заказ"))
        self.save_button.setText(_translate("about_customer", "Сохранить"))
        self.reset_button.setText(_translate("about_customer", "Сброс"))
        self.notes_button.setText(_translate("about_customer", "Заметки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    about_customer = QtWidgets.QMainWindow()
    ui = Ui_about_customer()
    ui.setupUi(about_customer)
    about_customer.show()
    sys.exit(app.exec_())
