# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_authorization(object):
    def setupUi(self, authorization):
        authorization.setObjectName("authorization")
        authorization.resize(287, 247)
        self.centralwidget = QtWidgets.QWidget(authorization)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 140, 171, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.info = QtWidgets.QLabel(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(60, 30, 171, 111))
        self.info.setObjectName("info")
        self.ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_button.setGeometry(QtCore.QRect(100, 170, 88, 27))
        self.ok_button.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.ok_button.setObjectName("ok_button")
        authorization.setCentralWidget(self.centralwidget)

        self.retranslateUi(authorization)
        QtCore.QMetaObject.connectSlotsByName(authorization)

    def retranslateUi(self, authorization):
        _translate = QtCore.QCoreApplication.translate
        authorization.setWindowTitle(_translate("authorization", "MainWindow"))
        self.info.setText(_translate("authorization", "      Авторизация\n"
"\n"
"\n"
"Введите ваш user code:"))
        self.ok_button.setText(_translate("authorization", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    authorization = QtWidgets.QMainWindow()
    ui = Ui_authorization()
    ui.setupUi(authorization)
    authorization.show()
    sys.exit(app.exec_())
