# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert_customer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_insert_customer(object):
    def setupUi(self, insert_customer):
        insert_customer.setObjectName("insert_customer")
        insert_customer.resize(357, 427)
        self.centralwidget = QtWidgets.QWidget(insert_customer)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 90, 68, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 150, 91, 19))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 270, 91, 19))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 30, 251, 19))
        self.label_5.setObjectName("label_5")
        self.name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_edit.setGeometry(QtCore.QRect(100, 120, 141, 21))
        self.name_edit.setObjectName("name_edit")
        self.lastname_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.lastname_edit.setGeometry(QtCore.QRect(100, 180, 141, 21))
        self.lastname_edit.setObjectName("lastname_edit")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 390, 181, 19))
        self.label_6.setObjectName("label_6")
        self.notes_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.notes_edit.setGeometry(QtCore.QRect(40, 300, 261, 71))
        self.notes_edit.setObjectName("notes_edit")
        self.to_order_button = QtWidgets.QPushButton(self.centralwidget)
        self.to_order_button.setGeometry(QtCore.QRect(110, 230, 121, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.to_order_button.setFont(font)
        self.to_order_button.setObjectName("to_order_button")
        insert_customer.setCentralWidget(self.centralwidget)

        self.retranslateUi(insert_customer)
        QtCore.QMetaObject.connectSlotsByName(insert_customer)

    def retranslateUi(self, insert_customer):
        _translate = QtCore.QCoreApplication.translate
        insert_customer.setWindowTitle(_translate("insert_customer", "MainWindow"))
        self.label.setText(_translate("insert_customer", "Имя*:"))
        self.label_2.setText(_translate("insert_customer", "Фамилия*:"))
        self.label_4.setText(_translate("insert_customer", "Заметки:"))
        self.label_5.setText(_translate("insert_customer", "Введите информацию о клиенте"))
        self.label_6.setText(_translate("insert_customer", "* - обязательное поле"))
        self.to_order_button.setText(_translate("insert_customer", "Перейти к заказу"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    insert_customer = QtWidgets.QMainWindow()
    ui = Ui_insert_customer()
    ui.setupUi(insert_customer)
    insert_customer.show()
    sys.exit(app.exec_())
