# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'products_button.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from designs.add_products import Ui_ProductEditor  # Импорт класса редактора продукта

class Ui_products(object):
    def setupUi(self, orders):
        orders.setObjectName("orders")
        orders.resize(959, 712)
        self.centralwidget = QtWidgets.QWidget(orders)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 30, 881, 581))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.add_product = QtWidgets.QPushButton(self.centralwidget)
        self.add_product.setGeometry(QtCore.QRect(40, 630, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.add_product.setFont(font)
        self.add_product.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.add_product.setObjectName("add_product")
        self.change_product = QtWidgets.QPushButton(self.centralwidget)
        self.change_product.setGeometry(QtCore.QRect(380, 630, 151, 41))
        self.change_product.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.change_product.setObjectName("change_product")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(740, 630, 91, 41))
        self.save_button.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.save_button.setObjectName("save_button")
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(840, 630, 81, 41))
        self.reset_button.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.reset_button.setObjectName("reset_button")
        self.remove_product = QtWidgets.QPushButton(self.centralwidget)
        self.remove_product.setGeometry(QtCore.QRect(200, 630, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.remove_product.setFont(font)
        self.remove_product.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.remove_product.setObjectName("remove_product")
        orders.setCentralWidget(self.centralwidget)

        self.retranslateUi(orders)
        QtCore.QMetaObject.connectSlotsByName(orders)

        self.add_product.clicked.connect(self.open_product_editor)


    def retranslateUi(self, orders):
        _translate = QtCore.QCoreApplication.translate
        orders.setWindowTitle(_translate("orders", "MainWindow"))
        self.add_product.setText(_translate("orders", "Добавить продукт"))
        self.change_product.setText(_translate("orders", "Изменить продукт"))
        self.save_button.setText(_translate("orders", "Сохранить"))
        self.reset_button.setText(_translate("orders", "Сброс"))
        self.remove_product.setText(_translate("orders", "Удалить продукт"))

    def open_product_editor(self):
        """Метод для открытия окна ProductEditor"""
        self.product_editor_window = QtWidgets.QMainWindow()
        self.product_editor = Ui_ProductEditor()
        self.product_editor.setupUi(self.product_editor_window)
        self.product_editor_window.setWindowModality(QtCore.Qt.ApplicationModal)
        self.product_editor_window.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    orders = QtWidgets.QMainWindow()
    ui = Ui_products()
    ui.setupUi(orders)
    orders.show()
    sys.exit(app.exec_())
