# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authorization_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Authorization(object):
    def setupUi(self, Authorization):
        Authorization.setObjectName("Authorization")
        Authorization.resize(218, 141)
        self.centralwidget = QtWidgets.QWidget(Authorization)
        self.centralwidget.setObjectName("centralwidget")
        self.ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_button.setGeometry(QtCore.QRect(70, 100, 75, 23))
        self.ok_button.setObjectName("ok_button")
        self.input_auth = QtWidgets.QLineEdit(self.centralwidget)
        self.input_auth.setGeometry(QtCore.QRect(20, 60, 181, 21))
        self.input_auth.setObjectName("input_auth")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 161, 16))
        self.label.setStyleSheet("font: 9pt \"Segoe MDL2 Assets\";")
        self.label.setObjectName("label")
        Authorization.setCentralWidget(self.centralwidget)

        self.retranslateUi(Authorization)
        QtCore.QMetaObject.connectSlotsByName(Authorization)

    def retranslateUi(self, Authorization):
        _translate = QtCore.QCoreApplication.translate
        Authorization.setWindowTitle(_translate("Authorization", "Авторизация"))
        self.ok_button.setText(_translate("Authorization", "OK"))
        self.label.setText(_translate("Authorization", "Введите ваш User_code"))
