# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customer_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomerForm(object):
    def setupUi(self, CustomerForm):
        CustomerForm.setObjectName("CustomerForm")
        CustomerForm.resize(269, 373)
        self.centralwidget = QtWidgets.QWidget(CustomerForm)
        self.centralwidget.setObjectName("centralwidget")
        self.name_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_line_edit.setGeometry(QtCore.QRect(30, 80, 211, 20))
        self.name_line_edit.setObjectName("name_line_edit")
        self.lastname_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.lastname_line_edit.setGeometry(QtCore.QRect(30, 130, 211, 20))
        self.lastname_line_edit.setObjectName("lastname_line_edit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 71, 20))
        self.label_2.setStyleSheet("font: 10pt \"MS Reference Sans Serif\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 71, 20))
        self.label_3.setStyleSheet("font: 10pt \"MS Reference Sans Serif\";")
        self.label_3.setObjectName("label_3")
        self.notes_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.notes_text_edit.setGeometry(QtCore.QRect(30, 240, 211, 71))
        self.notes_text_edit.setObjectName("notes_text_edit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 220, 71, 20))
        self.label_4.setStyleSheet("font: 10pt \"MS Reference Sans Serif\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 30, 171, 20))
        self.label_5.setStyleSheet("font: 10pt \"MS Reference Sans Serif\";")
        self.label_5.setObjectName("label_5")
        self.phone_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.phone_line_edit.setGeometry(QtCore.QRect(30, 180, 211, 20))
        self.phone_line_edit.setObjectName("phone_line_edit")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 160, 131, 20))
        self.label_6.setStyleSheet("font: 10pt \"MS Reference Sans Serif\";")
        self.label_6.setObjectName("label_6")
        self.add_or_change_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_or_change_button.setGeometry(QtCore.QRect(60, 330, 141, 23))
        self.add_or_change_button.setStyleSheet("font: 10pt \"MS Reference Sans Serif\";")
        self.add_or_change_button.setObjectName("add_or_change_button")
        CustomerForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(CustomerForm)
        QtCore.QMetaObject.connectSlotsByName(CustomerForm)

    def retranslateUi(self, CustomerForm):
        _translate = QtCore.QCoreApplication.translate
        CustomerForm.setWindowTitle(_translate("CustomerForm", "Информация о клиенте"))
        self.label_2.setText(_translate("CustomerForm", "Фамилия:"))
        self.label_3.setText(_translate("CustomerForm", "Имя:"))
        self.notes_text_edit.setPlaceholderText(_translate("CustomerForm", "*Необязательное поле"))
        self.label_4.setText(_translate("CustomerForm", "Заметки:"))
        self.label_5.setText(_translate("CustomerForm", "Информация о клиенте"))
        self.label_6.setText(_translate("CustomerForm", "Номер телефона:"))
        self.add_or_change_button.setText(_translate("CustomerForm", "Добавить/Изменить"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    phone_info = QtWidgets.QMainWindow()
    ui = Ui_CustomerForm()
    ui.setupUi(phone_info)
    phone_info.show()
    sys.exit(app.exec_())