# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phone_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PhoneInput(object):
    def setupUi(self, PhoneInput):
        PhoneInput.setObjectName("PhoneInput")
        PhoneInput.resize(223, 162)
        self.centralwidget = QtWidgets.QWidget(PhoneInput)
        self.centralwidget.setObjectName("centralwidget")
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(70, 120, 81, 23))
        self.next_button.setObjectName("next_button")
        self.phone_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.phone_line_edit.setGeometry(QtCore.QRect(30, 80, 161, 20))
        self.phone_line_edit.setText("")
        self.phone_line_edit.setObjectName("phone_line_edit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 151, 41))
        self.label.setStyleSheet("\n"
"font: 10pt \"Nirmala UI\";\n"
"text-align: center;")
        self.label.setObjectName("label")
        PhoneInput.setCentralWidget(self.centralwidget)

        self.retranslateUi(PhoneInput)
        QtCore.QMetaObject.connectSlotsByName(PhoneInput)

    def retranslateUi(self, PhoneInput):
        _translate = QtCore.QCoreApplication.translate
        PhoneInput.setWindowTitle(_translate("PhoneInput", "Номер телефона"))
        self.next_button.setText(_translate("PhoneInput", "Далее"))
        self.phone_line_edit.setPlaceholderText(_translate("PhoneInput", "*формат +375 XX XXX XX XX"))
        self.label.setWhatsThis(_translate("PhoneInput", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\"><br/>asd</span></p></body></html>"))
        self.label.setText(_translate("PhoneInput", "       Введите номер \n"
"     телефона клиента"))
